### PR TITLE
Move some of the helper functions into a SlackUtils module

### PR DESCRIPTION
**Pull request by hex337**
Some initial clean up, I have lots more to do.

### CODE REVIEW

**Comment by hex337** [comment]
All of the methods deal with finding things from the slack struct that we get. Maybe `SlackHelpers`?

**Comment by hex337** [comment]
I could clean up the inputs to always take the slack struct rather than parts of it, to unify the lib.

**Comment by nickcan** [comment]
1. `SlackDataHelpers` might be more explicit.
2. If everything comes through an http request and you know you need specific data, would it be beneficial to make a plug that parses the data onto the `conn` struct? Might be overkill, but seems relatively nice if you know you need it upon each request.

**Comment by nickcan** [comment]
I see this is more specific to each action. So maybe never mind on #2 of my last comment.

**Comment by hex337** [comment]
@nickcan I moved the module and named it SlackDataHelpers. I also started a refactor of the commands to move them out of the main slack file. Let me know if you think this is a good pattern.

I think I want the main slack file to only have things related to parsing the initial request and then pushing the rest of the logic into individual modules. It should mostly be a routing file.

**Pull request merged**
